const playerList = [
    { id: 1, name: 'Lionel Messi', gamesPlayed: 493 },
    { id: 2, name: 'Cristiano Ronaldo', gamesPlayed: 510 },
    { id: 3, name: 'Neymar Jr', gamesPlayed: 384 },
    { id: 4, name: 'Kylian Mbappe', gamesPlayed: 295 },
    { id: 5, name: 'Robert Lewandowski', gamesPlayed: 420 },
    { id: 6, name: 'Kevin De Bruyne', gamesPlayed: 375 },
    { id: 7, name: 'Virgil van Dijk', gamesPlayed: 321 },
    { id: 8, name: 'Sergio Ramos', gamesPlayed: 468 },
    { id: 9, name: 'Harry Kane', gamesPlayed: 325 },
    { id: 10, name: 'Luka Modric', gamesPlayed: 414 },
    { id: 11, name: 'Eden Hazard', gamesPlayed: 322 },
    { id: 12, name: 'Paul Pogba', gamesPlayed: 318 },
    { id: 13, name: 'Antoine Griezmann', gamesPlayed: 361 },
    { id: 14, name: 'Zlatan Ibrahimovic', gamesPlayed: 502 },
    { id: 15, name: 'Mohamed Salah', gamesPlayed: 376 },
    { id: 16, name: 'Sadio Mane', gamesPlayed: 369 },
    { id: 17, name: 'Raheem Sterling', gamesPlayed: 347 },
    { id: 18, name: 'Sergio Aguero', gamesPlayed: 421 },
    { id: 19, name: 'Karim Benzema', gamesPlayed: 438 },
    { id: 20, name: 'Marcelo', gamesPlayed: 412 },
    { id: 21, name: 'Gerard Pique', gamesPlayed: 401 },
    { id: 22, name: 'Toni Kroos', gamesPlayed: 358 },
    { id: 23, name: 'Manuel Neuer', gamesPlayed: 467 },
    { id: 24, name: 'Gianluigi Buffon', gamesPlayed: 485 },
    { id: 25, name: 'Thomas Muller', gamesPlayed: 419 },
    { id: 26, name: 'Alisson Becker', gamesPlayed: 341 },
    { id: 27, name: 'Joshua Kimmich', gamesPlayed: 328 },
    { id: 28, name: 'Trent Alexander-Arnold', gamesPlayed: 303 },
    { id: 29, name: 'Andrew Robertson', gamesPlayed: 311 },
    { id: 30, name: 'Romelu Lukaku', gamesPlayed: 399 },
    { id: 31, name: 'Fabinho', gamesPlayed: 356 },
    { id: 32, name: 'Aymeric Laporte', gamesPlayed: 337 },
    { id: 33, name: 'Ederson Moraes', gamesPlayed: 389 },
    { id: 34, name: 'Jan Oblak', gamesPlayed: 401 },
    { id: 35, name: 'Bernardo Silva', gamesPlayed: 332 },
    { id: 36, name: 'Joao Felix', gamesPlayed: 297 },
    { id: 37, name: 'Thiago Alcantara', gamesPlayed: 341 },
    { id: 38, name: 'Casemiro', gamesPlayed: 368 },
    { id: 39, name: 'Jadon Sancho', gamesPlayed: 295 },
    { id: 40, name: 'Hakim Ziyech', gamesPlayed: 281 },
    { id: 41, name: 'Mats Hummels', gamesPlayed: 379 },
    { id: 42, name: 'Marco Reus', gamesPlayed: 383 },
    { id: 43, name: 'Kingsley Coman', gamesPlayed: 323 },
    { id: 44, name: 'Philippe Coutinho', gamesPlayed: 332 },
    { id: 45, name: 'Luis Suarez', gamesPlayed: 455 },
    { id: 46, name: 'David Silva', gamesPlayed: 435 },
    { id: 47, name: 'Ciro Immobile', gamesPlayed: 387 },
    { id: 48, name: 'Lautaro Martinez', gamesPlayed: 303 },
    { id: 49, name: 'James Rodriguez', gamesPlayed: 325 },
    { id: 50, name: 'Christian Eriksen', gamesPlayed: 342 },
    { id: 51, name: 'Leon Goretzka', gamesPlayed: 315 },
    { id: 52, name: 'Arthur Melo', gamesPlayed: 290 },
    { id: 53, name: 'Miralem Pjanic', gamesPlayed: 361 },
    { id: 54, name: 'Alex Sandro', gamesPlayed: 324 },
    { id: 55, name: 'Rodri', gamesPlayed: 349 },
    { id: 56, name: 'Richarlison', gamesPlayed: 279 },
    { id: 57, name: 'Gerard Moreno', gamesPlayed: 332 },
    { id: 58, name: 'Ilkay Gundogan', gamesPlayed: 386 },
    { id: 59, name: 'Pierre-Emerick Aubameyang', gamesPlayed: 408 },
    { id: 60, name: 'Kalidou Koulibaly', gamesPlayed: 377 },
    { id: 61, name: 'Wilfred Ndidi', gamesPlayed: 299 },
    { id: 62, name: 'Danny Ings', gamesPlayed: 294 },
    { id: 63, name: 'Timo Werner', gamesPlayed: 316 },
    { id: 64, name: 'Lucas Hernandez', gamesPlayed: 289 },
    { id: 65, name: 'Mason Mount', gamesPlayed: 271 },
    { id: 66, name: 'Declan Rice', gamesPlayed: 309 },
    { id: 67, name: 'Youri Tielemans', gamesPlayed: 318 },
    { id: 68, name: 'Ben Chilwell', gamesPlayed: 273 },
    { id: 69, name: 'Giovanni Lo Celso', gamesPlayed: 287 },
    { id: 70, name: 'Federico Valverde', gamesPlayed: 295 },
    { id: 71, name: 'Ansu Fati', gamesPlayed: 219 },
    { id: 72, name: 'Alphonso Davies', gamesPlayed: 256 },
    { id: 73, name: 'Achraf Hakimi', gamesPlayed: 268 },
    { id: 74, name: 'Dayot Upamecano', gamesPlayed: 271 },
    { id: 75, name: 'Martin Odegaard', gamesPlayed: 279 },
    { id: 76, name: 'Dani Olmo', gamesPlayed: 283 },
    { id: 77, name: 'Nicolo Barella', gamesPlayed: 292 },
    { id: 78, name: 'Isco', gamesPlayed: 324 },
    { id: 79, name: 'Vinicius Jr', gamesPlayed: 269 },
    { id: 80, name: 'Rodrygo', gamesPlayed: 235 },
    { id: 81, name: 'Frenkie de Jong', gamesPlayed: 338 },
    { id: 82, name: 'Matthijs de Ligt', gamesPlayed: 319 },
    { id: 83, name: 'Pedri', gamesPlayed: 198 },
    { id: 84, name: 'Mikel Oyarzabal', gamesPlayed: 285 },
    { id: 85, name: 'Marcus Rashford', gamesPlayed: 342 },
    { id: 86, name: 'Mason Greenwood', gamesPlayed: 211 },
    { id: 87, name: 'Phil Foden', gamesPlayed: 278 },
    { id: 88, name: 'Dominik Szoboszlai', gamesPlayed: 204 },
    { id: 89, name: 'Eduardo Camavinga', gamesPlayed: 191 },
    { id: 90, name: 'Jude Bellingham', gamesPlayed: 215 },
    { id: 91, name: 'Ryan Gravenberch', gamesPlayed: 192 },
    { id: 92, name: 'Sergino Dest', gamesPlayed: 203 },
    { id: 93, name: 'Bukayo Saka', gamesPlayed: 227 },
    { id: 94, name: 'Giovanni Reyna', gamesPlayed: 184 },
    { id: 95, name: 'Emile Smith Rowe', gamesPlayed: 168 },
    { id: 96, name: 'Erling Haaland', gamesPlayed: 258 },
    { id: 97, name: 'Joao Cancelo', gamesPlayed: 310 },
    { id: 98, name: 'Kai Havertz', gamesPlayed: 297 },
    { id: 99, name: 'Ferran Torres', gamesPlayed: 267 },
    { id: 100, name: 'Pedri', gamesPlayed: 198 },
];

export default playerList;
