const playerList = [
    { 
        id: 1, 
        name: 'Lionel Messi', 
        gamesPlayed: 493,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        },
        trendsLastGames: [1,2,3,4,2,3,1,2,3,4],
    },
    { 
        id: 2, 
        name: 'Cristiano Ronaldo', 
        gamesPlayed: 510,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        },
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        },
    },
    { 
        id: 3, 
        name: 'Neymar Jr', 
        gamesPlayed: 384,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        },
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        },
    },
    { 
        id: 4, 
        name: 'Kylian Mbappe', 
        gamesPlayed: 295,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        },
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        },
    },
    { 
        id: 5, 
        name: 'Robert Lewandowski', 
        gamesPlayed: 420,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        }, 
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        },
    },
    { 
        id: 6, 
        name: 'Kevin De Bruyne', 
        gamesPlayed: 375,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        }, 
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        },
    },
    { 
        id: 7, 
        name: 'Virgil van Dijk', 
        gamesPlayed: 321,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        },
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        }, 
    },
    { 
        id: 8, 
        name: 'Sergio Ramos', 
        gamesPlayed: 468,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        },
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        }, 
    },
    { 
        id: 9, 
        name: 'Harry Kane', 
        gamesPlayed: 325,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        },
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        }, 
    },
    { 
        id: 10, 
        name: 'Luka Modric', 
        gamesPlayed: 414,
        playerStats: {
            soulIdPlayer: 1,
            placeRank: 1,
            playerRank: 1,
            avarangePlace: 1.5,
            shareOfGamesPlayed: 0.5,
            averangeIncrement: 0.5,
            persentageFirstPlace: 0.5,
            persentageSecondPlace: 0.5,
            persentageThirdPlace: 0.5,
            persentageFourthPlace: 0.5,
            persentageOfNegativeRank: 0.5,
            persentageOfGamesPlayedFromAll: 0.5,
            sumOfPoints: 0.5,
            amountOfRatingEarned: 0.5,
            maxPoints: 0.5,
            minPoints: 0.5,
            averangePoints: 0.5,
        },
        trendsLastGames: {
            gameOne: 1,
            gameTwo: 2,
            gameThree: 3,
            gameFour: 4,
            gameFive: 2,
            gameSix: 3,
            gameSeven: 1,
            gameEight: 2,
            gameNine: 3,
            gameTen: 4,
        }, 
    },
];

export default playerList;
